spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialSize: 5
        maxActive: 20
        maxWait: 60000
        minIdle: 5
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:postgresql://127.0.0.1:5432/quark_community?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: postgres
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
